version: "3.8"
services:
    sqlserver:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        ports:
            - '1433:1433'
        volumes:
            - sqldata:/var/opt/mssql/sqlserver
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        deploy:
          resources:
            reservations:
              cpus: '2'
              memory: 2GB
    web-app:
        container_name: webapp
        image: contactslibrary.azurecr.io/contacts
        domainname: yanabg
        ports:
          - '80:80'
        restart: on-failure

#networks:
#    contacts:
#        external: true
#        name: contacts
volumes:
    sqldata:
#        external: true

        driver: azure_file
        driver_opts:
          share_name: sql-volume
          storage_account_name: contactsstorageaccybg

       